module.exports=function(app,pool){
const rows=async(sql,p=[])=>(await pool.query(sql,p)).rows;
app.get('/api/business/summary',async(q,s)=>{try{const one=async(sql,p=[])=>(await rows(sql,p))[0];s.json({lowStock:await one("SELECT COUNT(*)::int count FROM products WHERE quantity<=low_stock_level"),inventory:await one("SELECT COALESCE(SUM(quantity*cost_price),0) cost_value,COALESCE(SUM(quantity*price),0) sale_value FROM products"),profit:await one("SELECT COALESCE(SUM(total-(cost_price*qty)),0) total FROM orders WHERE status NOT IN ('cancelled','returned')"),customers:await one("SELECT COUNT(*)::int count FROM customers")})}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/products/:id/stock-in',async(q,s)=>{try{const n=Number(q.body.qty)||0;if(n<=0)return s.status(400).json({error:'Quantity must be greater than 0'});const p=(await pool.query("UPDATE products SET quantity=quantity+$1,updated_at=NOW() WHERE id=$2 RETURNING *",[n,q.params.id])).rows[0];if(!p)return s.status(404).json({error:'Product not found'});await pool.query("INSERT INTO stock_movements(product_id,product_title,sku,type,qty,note) VALUES($1,$2,$3,'stock_in',$4,$5)",[p.id,p.title,p.sku,n,q.body.note||'Stock received']);s.json(p)}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/stock-movements',async(q,s)=>{try{s.json(await rows("SELECT * FROM stock_movements ORDER BY created_at DESC,id DESC LIMIT 1000"))}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/suppliers',async(q,s)=>{try{s.json(await rows("SELECT * FROM suppliers ORDER BY name"))}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/suppliers',async(q,s)=>{try{const x=q.body;if(!String(x.name||'').trim())return s.status(400).json({error:'Supplier name required'});s.json((await pool.query("INSERT INTO suppliers(name,phone,email,note) VALUES($1,$2,$3,$4) RETURNING *",[x.name,x.phone||'',x.email||'',x.note||''])).rows[0])}catch(e){s.status(500).json({error:e.message})}});
app.delete('/api/suppliers/:id',async(q,s)=>{try{await pool.query("DELETE FROM suppliers WHERE id=$1",[q.params.id]);s.json({ok:true})}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/customers/:id/orders',async(q,s)=>{try{const c=(await rows("SELECT * FROM customers WHERE id=$1",[q.params.id]))[0];if(!c)return s.json([]);s.json(await rows("SELECT * FROM orders WHERE (customer_phone<>'' AND customer_phone=$1) OR (customer_email<>'' AND customer_email=$2) ORDER BY created_at DESC",[c.phone||'',c.email||'']))}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/profit-report',async(q,s)=>{try{const days=Math.max(1,Math.min(Number(q.query.days)||30,3650));const sales=(await rows("SELECT COALESCE(SUM(total),0) total FROM orders WHERE status NOT IN ('cancelled','returned') AND created_at>=NOW()-make_interval(days=>$1)",[days]))[0];const expenses=(await rows("SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE created_at>=NOW()-make_interval(days=>$1)",[days]))[0];const gross=(await rows("SELECT COALESCE(SUM(total-(cost_price*qty)),0) total FROM orders WHERE status NOT IN ('cancelled','returned') AND created_at>=NOW()-make_interval(days=>$1)",[days]))[0];const inventory=(await rows("SELECT COALESCE(SUM(quantity*cost_price),0) cost_value,COALESCE(SUM(quantity*price),0) sale_value FROM products"))[0];const articles=await rows("SELECT COALESCE(p.title,'Unknown') article,COUNT(*)::int orders,COALESCE(SUM(o.qty),0)::int units,COALESCE(SUM(o.total-(o.cost_price*o.qty)),0) profit FROM orders o LEFT JOIN products p ON p.id=o.product_id WHERE o.status NOT IN ('cancelled','returned') GROUP BY p.title ORDER BY profit DESC LIMIT 50");s.json({days,sales:sales.total,expenses:expenses.total,gross_profit:gross.total,net_profit:Number(gross.total)-Number(expenses.total),inventory,articles})}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/export/:type',async(q,s)=>{try{const map={orders:'SELECT * FROM orders ORDER BY id',customers:'SELECT * FROM customers ORDER BY id',inventory:'SELECT * FROM products ORDER BY id',expenses:'SELECT * FROM expenses ORDER BY id',suppliers:'SELECT * FROM suppliers ORDER BY id'};const sql=map[q.params.type];if(!sql)return s.status(404).json({error:'Invalid export'});const data=await rows(sql);if(!data.length){s.type('text/csv');return s.send('No data')}const keys=Object.keys(data[0]);const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';s.setHeader('Content-Disposition',`attachment; filename=${q.params.type}.csv`);s.type('text/csv').send(keys.join(',')+'\n'+data.map(r=>keys.map(k=>esc(r[k])).join(',')).join('\n'))}catch(e){s.status(500).json({error:e.message})}});
};