require("dotenv").config();
const express=require("express"),cors=require("cors"),path=require("path");
const {pool,initDb}=require("./db"),{login,auth}=require("./auth");
const app=express();app.use(cors());
app.post("/api/login",express.json(),async(req,res)=>{try{const x=await login(req.body.email,req.body.password);if(!x)return res.status(401).json({error:"Invalid email or password"});res.json(x)}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/health",(q,s)=>s.json({ok:true}));
app.use(express.json({limit:"2mb"}));app.use("/api",auth);
const rows=async(sql,p=[])=>{const r=await pool.query(sql,p);return r.rows};
app.get("/api/dashboard",async(req,res)=>{try{const q=async(s)=>rows(s).then(x=>x[0]);res.json({orders:await q("SELECT COUNT(*)::int count,COALESCE(SUM(total),0) total FROM orders"),products:await q("SELECT COUNT(*)::int count,COALESCE(SUM(quantity),0) stock FROM products"),expenses:await q("SELECT COALESCE(SUM(amount),0) total FROM expenses"),receivable:await q("SELECT COALESCE(SUM(amount-paid),0) total FROM khata WHERE type='receivable'"),payable:await q("SELECT COALESCE(SUM(amount-paid),0) total FROM khata WHERE type='payable'"),customers:await q("SELECT COUNT(*)::int count FROM customers"),production:await q("SELECT COALESCE(SUM((fabric+stitching+embroidery+printing+packaging+other_cost)*qty),0) total FROM production")})}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/orders",async(q,s)=>s.json(await rows("SELECT * FROM orders ORDER BY order_date DESC NULLS LAST,id DESC LIMIT 1000")));
app.get("/api/products",async(q,s)=>s.json(await rows("SELECT * FROM products ORDER BY title")));
app.get("/api/customers",async(q,s)=>s.json(await rows("SELECT * FROM customers ORDER BY name")));
app.get("/api/expenses",async(q,s)=>s.json(await rows("SELECT * FROM expenses ORDER BY spent_at DESC,id DESC")));
app.post("/api/expenses",async(q,s)=>{const x=q.body;s.json((await pool.query("INSERT INTO expenses(title,category,amount,note,spent_at) VALUES($1,$2,$3,$4,$5) RETURNING *",[x.title,x.category,x.amount,x.note,x.spent_at||null])).rows[0])});
app.delete("/api/expenses/:id",async(q,s)=>{await pool.query("DELETE FROM expenses WHERE id=$1",[q.params.id]);s.json({ok:true})});
app.get("/api/khata",async(q,s)=>s.json(await rows("SELECT *,amount-paid AS remaining FROM khata ORDER BY created_at DESC")));
app.post("/api/khata",async(q,s)=>{const x=q.body;s.json((await pool.query("INSERT INTO khata(type,person,amount,paid,due_date,description,notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *,amount-paid AS remaining",[x.type,x.person,x.amount,x.paid||0,x.due_date||null,x.description||"",x.notes||""])).rows[0])});
app.patch("/api/khata/:id",async(q,s)=>{const x=q.body;s.json((await pool.query("UPDATE khata SET paid=$1 WHERE id=$2 RETURNING *,amount-paid AS remaining",[x.paid,q.params.id])).rows[0])});
app.delete("/api/khata/:id",async(q,s)=>{await pool.query("DELETE FROM khata WHERE id=$1",[q.params.id]);s.json({ok:true})});
app.get("/api/production",async(q,s)=>s.json(await rows("SELECT *,((fabric+stitching+embroidery+printing+packaging+other_cost)) unit_cost,((fabric+stitching+embroidery+printing+packaging+other_cost)*qty) total_cost FROM production ORDER BY created_at DESC")));
app.post("/api/production",async(q,s)=>{const x=q.body;s.json((await pool.query("INSERT INTO production(article,qty,fabric,stitching,embroidery,printing,packaging,other_cost) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[x.article,x.qty||1,x.fabric||0,x.stitching||0,x.embroidery||0,x.printing||0,x.packaging||0,x.other_cost||0])).rows[0])});
app.delete("/api/production/:id",async(q,s)=>{await pool.query("DELETE FROM production WHERE id=$1",[q.params.id]);s.json({ok:true})});
app.get("/api/payments",async(q,s)=>s.json(await rows("SELECT * FROM payments ORDER BY paid_at DESC,id DESC")));
app.post("/api/payments",async(q,s)=>{const x=q.body;s.json((await pool.query("INSERT INTO payments(vendor,amount,method,note,paid_at) VALUES($1,$2,$3,$4,$5) RETURNING *",[x.vendor,x.amount,x.method,x.note,x.paid_at||null])).rows[0])});
app.get("/api/invoices",async(q,s)=>s.json(await rows("SELECT * FROM invoices ORDER BY created_at DESC")));
app.post("/api/invoices",async(q,s)=>{const x=q.body;const no=x.invoice_no||`NURA-${Date.now()}`;s.json((await pool.query("INSERT INTO invoices(invoice_no,customer_name,customer_phone,items,total,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[no,x.customer_name,x.customer_phone,JSON.stringify(x.items||[]),x.total||0,x.status||"unpaid"])).rows[0])});
app.delete("/api/invoices/:id",async(q,s)=>{await pool.query("DELETE FROM invoices WHERE id=$1",[q.params.id]);s.json({ok:true})});
app.get("/api/settings",async(q,s)=>s.json((await rows("SELECT * FROM settings WHERE id=1"))[0]||{}));
app.put("/api/settings",async(q,s)=>{const x=q.body;s.json((await pool.query(`INSERT INTO settings(id,brand_name,currency,delivery_fee,free_delivery_above) VALUES(1,$1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET brand_name=EXCLUDED.brand_name,currency=EXCLUDED.currency,delivery_fee=EXCLUDED.delivery_fee,free_delivery_above=EXCLUDED.free_delivery_above RETURNING *`,[x.brand_name,x.currency,x.delivery_fee,x.free_delivery_above])).rows[0]);});
app.get("/api/reports",async(q,s)=>{try{const sales=await rows("SELECT COALESCE(SUM(total),0) AS total FROM orders"),exp=await rows("SELECT COALESCE(SUM(amount),0) AS total FROM expenses"),cost=await rows("SELECT COALESCE(SUM((fabric+stitching+embroidery+printing+packaging+other_cost)*qty),0) AS total FROM production"),monthly=await rows(`SELECT TO_CHAR(COALESCE(order_date,created_at),'YYYY-MM') AS "month", COUNT(*) AS "orders", COALESCE(SUM(total),0) AS "sales" FROM orders GROUP BY TO_CHAR(COALESCE(order_date,created_at),'YYYY-MM') ORDER BY TO_CHAR(COALESCE(order_date,created_at),'YYYY-MM') DESC LIMIT 12`);s.json({sales:sales[0],expenses:exp[0],productionCost:cost[0],monthly})}catch(e){s.status(500).json({error:e.message})}});
app.use(express.static(__dirname));app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"index.html")));
initDb().then(()=>app.listen(process.env.PORT||3000,"0.0.0.0",()=>console.log("Nura ERP ready"))).catch(e=>{console.error(e);process.exit(1)});
